import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../src/worker.js';
function setup(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0001.sql',import.meta.url),'utf8'));const env={DB:{prepare(sql){return {bind(...args){const st=db.prepare(sql);return {async first(){return st.get(...args)||null;},async all(){return {results:st.all(...args)};},async run(){return st.run(...args);}}; }};},async batch(statements){db.exec('BEGIN');try{const r=[];for(const st of statements)r.push(await st.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}},ASSETS:{fetch:async()=>new Response('asset')}};let cookie='';async function req(path,data){const headers={Origin:'https://bet.test',...(data?{'Content-Type':'application/json'}:{}),Cookie:cookie};const res=await worker.fetch(new Request('https://bet.test/api/'+path,{method:data?'POST':'GET',headers,body:data?JSON.stringify(data):undefined}),env);if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];return {status:res.status,data:await res.json()};}return {db,env,req};}
async function user(s,email='player@example.com'){assert.equal((await s.req('register',{name:'Jogador',email,password:'password-123456'})).status,200);return (await s.req('me')).data;}
function event(db){const t=Math.floor(Date.now()/1000);db.prepare('INSERT INTO events VALUES(?,?,?,?,?,?)').run('event','Luta teste','Lutas',t+3600,'open',null);db.prepare('INSERT INTO outcomes VALUES(?,?,?,?)').run('a','event','Azul',250);db.prepare('INSERT INTO outcomes VALUES(?,?,?,?)').run('b','event','Vermelho',180);}
test('cadastro, senha, privacidade e acesso admin',async()=>{const s=setup();assert.equal((await s.req('me')).status,401);await user(s);assert.equal((await s.req('me')).data.balance,1000);assert.equal((await s.req('admin/data')).status,403);assert.equal((await s.req('me')).data.password,undefined);await s.req('logout',{});assert.equal((await s.req('login',{email:'player@example.com',password:'senha-errada-longa'})).status,401);assert.equal((await s.req('login',{email:'player@example.com',password:'password-123456'})).status,200);});
test('aposta debita, impede saldo negativo e duplicação, paga uma única vez',async()=>{const s=setup();await user(s);event(s.db);assert.equal((await s.req('bet',{id:'ticket-00001',outcome:'a',stake:100})).status,200);assert.equal((await s.req('me')).data.balance,900);assert.equal((await s.req('bet',{id:'ticket-00001',outcome:'a',stake:100})).status,409);assert.equal((await s.req('bet',{id:'ticket-00002',outcome:'a',stake:1000})).status,409);assert.equal(s.db.prepare('SELECT count(*) n FROM bets').get().n,1);s.db.exec("UPDATE users SET role='admin'");assert.equal((await s.req('admin/settle',{event:'event',winner:'a'})).status,200);assert.equal((await s.req('me')).data.balance,1150);assert.equal((await s.req('admin/settle',{event:'event',winner:'a'})).status,409);assert.equal((await s.req('bet',{id:'ticket-00003',outcome:'a',stake:1})).status,409);});
test('bônus diário e código têm uso único, estoque e janela',async()=>{const s=setup();await user(s);assert.equal((await s.req('daily',{})).status,200);assert.equal((await s.req('daily',{})).status,409);const t=Math.floor(Date.now()/1000);s.db.prepare('INSERT INTO bonuses VALUES(?,?,?,?,?,?)').run('TESTE',200,t-10,t+100,1,0);assert.equal((await s.req('bonus',{code:'teste'})).status,200);assert.equal((await s.req('bonus',{code:'teste'})).status,409);await user(s,'second@example.com');assert.equal((await s.req('bonus',{code:'teste'})).status,409);assert.equal((await s.req('me')).data.balance,1000);});
test('prêmio tem estoque, saldo e devolução atômica sem duplicar',async()=>{const s=setup();await user(s);const t=Math.floor(Date.now()/1000);s.db.prepare('INSERT INTO prizes VALUES(?,?,?,?,?,?,?,?)').run('prize','Prêmio','Descrição',500,1,t-10,t+100,1);assert.equal((await s.req('redeem',{id:'redeem-0001',prize:'prize'})).status,200);assert.equal((await s.req('redeem',{id:'redeem-0002',prize:'prize'})).status,409);assert.equal((await s.req('me')).data.balance,500);s.db.exec("UPDATE users SET role='admin'");assert.equal((await s.req('admin/redemption',{id:'redeem-0001',status:'refunded'})).status,200);assert.equal((await s.req('me')).data.balance,1000);assert.equal(s.db.prepare('SELECT stock FROM prizes').get().stock,1);assert.equal((await s.req('admin/redemption',{id:'redeem-0001',status:'refunded'})).status,409);});
test('cancelamento restitui apostas e resultado inválido não altera carteira',async()=>{const s=setup();await user(s);event(s.db);await s.req('bet',{id:'ticket-00001',outcome:'b',stake:100});s.db.exec("UPDATE users SET role='admin'");assert.equal((await s.req('admin/settle',{event:'event',winner:'inexistente'})).status,409);assert.equal((await s.req('me')).data.balance,900);assert.equal((await s.req('admin/settle',{event:'event',cancel:true})).status,200);assert.equal((await s.req('me')).data.balance,1000);});
test('rejeita requisição de outra origem e payload excessivo',async()=>{const s=setup();let res=await worker.fetch(new Request('https://bet.test/api/register',{method:'POST',headers:{Origin:'https://evil.test','Content-Type':'application/json'},body:'{}'}),s.env);assert.equal(res.status,403);res=await worker.fetch(new Request('https://bet.test/api/register',{method:'POST',headers:{Origin:'https://bet.test','Content-Type':'application/json'},body:JSON.stringify({large:'x'.repeat(17000)})}),s.env);assert.equal(res.status,413);});
test('ativação administrativa exige código privado e funciona uma única vez',async()=>{const s=setup();await user(s);assert.equal((await s.req('activate-admin',{code:'a'.repeat(64)})).status,403);s.env.SETUP_HASH=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('a'.repeat(64)))).toString('hex');assert.equal((await s.req('activate-admin',{code:'b'.repeat(64)})).status,403);assert.equal((await s.req('activate-admin',{code:'a'.repeat(64)})).status,200);assert.equal((await s.req('me')).data.role,'admin');await user(s,'another@example.com');assert.equal((await s.req('activate-admin',{code:'a'.repeat(64)})).status,409);assert.equal((await s.req('me')).data.role,'user');});
